#!/usr/bin/perl
#
# Tool to print stack traces from raw stack traces generated by McRTOS
#
# Invocation syntax:
# gen_call_graph.pl <ELF file> <raw stack trace file>
#
# Author: German Rivera - March, 2015
#
use strict;
use warnings;
use File::Basename;
use File::Path;
use IPC::Open2;
#use Carp::Assert;

#
# Global variables
#
my $MULTIPLE_NAMES_FILE_NAME = "Defined in multiple files";

#
# Name of this tool
#
my $PROG_NAME = basename($0);

my $USAGE_STR = "Usage: $PROG_NAME <ELF file> < <raw stack trace file>";

#
# Main program
#
{
    my $elf_file;
    my $raw_stack_trace_file;
    my $result;

    if (@ARGV != 1)
    {
        my $num_args = @ARGV;
        die "*** Error: Invalid number of arguments: $num_args (@ARGV)\n$USAGE_STR\n";
    }

    ($elf_file) = @ARGV;

    while (<STDIN>) {
        chomp $_;
        $_ =~ s/^\s+//;     # trim leading white spaces
        my @record = split /[ \t]/, $_;
        if (@record == 0) {
            next;
        }

        my $call_addr = $record[0];
        system "addr2line -e $elf_file -afps $call_addr";
    }

    exit 0;
}

